[phases.setup]
  aptPkgs = ['wget']
[phases.downloadTessdata]
  cmds = ['wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -O ./tessdata/eng.traineddata']
[phases.setupTesseract]
  cmds = ['export TESSDATA_PREFIX=./tessdata']
[phases.name]
  nixLibs = ['libheif']
  nixPkgs = ["tesseract", "tesseract5"]
[phases.build]
  cmds = ['pip uninstall opencv-python -y && pip uninstall opencv-python-headless -y && pip install opencv-python-headless']


